добавлена вёрстка первой части
DOCtorascz/MyFirstReposit-vers2- pull request #15
Opened 2023-01-13 06:51 UTC by DOCtorascz

2023-01-13 11:12 UTC, burtovoy requested changes
1. В css отступы нужны
2. Загрузи куда-нибудь для демонстрации пожалуйста, я добавлю это в задание
3. Не вижу подключения шрифта lato?

2023-01-13 14:46 UTC, DOCtorascz commented
https://stackblitz.com/edit/web-platform-xeqcur?file=styles.css - ссылка, только картинка не привязалась

2023-01-16 13:30 UTC, burtovoy requested changes

2023-01-16 13:30 UTC, burtovoy commented on style.css
> + text-align: center;
используем 2 отступа

2023-01-16 13:30 UTC, burtovoy commented on style.css
> + font-family: inherit;
без этого не получится? уже указано для body

2023-01-17 11:23 UTC, merged