Верстка Decktop
DOCtorascz/MyFirstReposit-vers2- pull request #59
Opened 2023-03-28 16:30 UTC by DOCtorascz

2023-03-29 22:43 UTC, burtovoy requested changes
Не задеплоено?

2023-03-30 02:50 UTC, DOCtorascz commented
> Не задеплоено?

в ветке master, если сделаешь merge, должно обновиться

2023-03-31 08:51 UTC, DOCtorascz commented
> Не задеплоено?

вёрстку переделал в оригинальном проекте смотриться как на макете, рендер почему-то стили не грузит

2023-04-03 08:40 UTC, burtovoy requested changes
Обсудили голосом

2023-04-08 02:48 UTC, DOCtorascz commented
> Отлично! Стало гораздо лучше. Нужно разобраться с конфликтами и я смерджу. Есть нюансы - я их ввиду isssue сделаю - на 95% все хорошо

Конфликтов нет

2023-04-09 11:27 UTC, merged